swagger: '2.0'
info:
  description: 'This is a sample server Petstore server.'
  version: '1.0.0'
  title: 'Swagger Petstore'
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: 'apiteam@swagger.io'
  license:
    name: 'Apache 2.0'
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: 'petstore.swagger.io'
basePath: '/v2'
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json
  - application/xml
tags:
  - name: 'pet'
    description: 'Everything about your Pets'
    externalDocs:
      description: 'Find out more'
      url: 'http://swagger.io'
schemes:
  - 'http'
paths:
  /pet:
    post:
      tags:
        - 'pet'
      summary: 'Add a new pet to the store'
      description: 'post a pet to store'
      operationId: 'add_pet'
      consumes:
        - 'application/xml'
      produces:
        - 'application/xml'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'Pet object that needs to be added to the store'
          required: true
          schema:
            $ref: '#/definitions/Pet'
      responses:
        200:
          description: example description
        405:
          description: 'Invalid input'
definitions:
  Pet:
    type: 'object'
    description: 'string'
    required:
      - 'name'
      - 'photo_urls'
    properties:
      id:
        type: 'integer'
        format: 'int64'
        description: 'string'
      name:
        type: 'string'
        example: 'doggie'
        description: 'string'
