openapi: 3.0.0
info:
  title: Example OpenAPI 3 definition.
  version: 1.0
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html

paths:
  /pet/findByStatus:
    get:
      responses:
        '200':
          description: example description