openapi: 3.1.0
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0

paths:
  /some:
    get:
      responses:
        '200':
          content:
            application/json:
              schema:
                type:
                  - integer
                  - array
                enum:
                  - 1
                  - [1, 2, 3, string]
                  - 3
          userId:
            application/json:
              schema:
              type:
                - integer
              enum:
                - 1
                - 2
                - 13
