openapi: 3.1.0
info:
  title: Example OpenAPI 3 definition.
  version: 1.0

paths:
  /pet/findByStatus:
    get:
      summary: example summary
      operationId: getPetsByStatus
      responses:
        '200':
          description: example description
