openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  description: Some description
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://development.com/v1

paths:
  '/api/user/{}/profie':
    get:
      operationId: getUserProfile
      summary: Example summary
      responses:
        '200':
          description: example description
