openapi: 3.0.0
servers:
  - url: //petstore.swagger.io/v2
    description: Default server
info:
  title: Example OpenAPI 3 definition.
  version: 1.0.0
  description: some description
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: qa
    url: https://swagger.io/specification/#definitions
    email: email@redocly.com

paths:
  /pet/findByPut:
    get:
      operationId: example
      summary: summary example
      responses:
        '200':
          description: example description
  /getCustomers:
    get:
      operationId: customerId
      summary: get customers example
      responses:
        '200':
          description: example description
  /PUTImages:
    get:
      operationId: imageId
      summary: put images example
      responses:
        '200':
          description: example description
  /GET-customers:
    get:
      operationId: getCustomerId
      summary: get customers example
      responses:
        '200':
          description: example description
  /my_post:
    get:
      operationId: postId
      summary: my post example
      responses:
        '200':
          description: example description
  /dispute:
    get:
      operationId: disputeId
      summary: dispute example
      responses:
        '200':
          description: example description
  /input:
    get:
      operationId: inputId
      summary: input example
      responses:
        '200':
          description: example description
