openapi: 3.0.0
info:
  title: Example OpenAPI 3 definition.
  version: 1.0
  license: blah #name field is required in license object

paths:
  /pet/findByStatus:
    get:
      responses:
        '200':
          description: example description