openapi: 3.1.0
info:
  title: Example OpenAPI 3 definition.
  version: 1.0

paths:
  '/ping':
    get:
      operationId: gitPing
      summary: example text
      responses:
        '200':
          description: example description
