openapi: 3.1.0
servers:
  - url: http://example.xyz
info:
  license:
    name: test licence
    url: http://example.xyz
  title: Example OpenAPI 3 definition.
  description: Example description.
  version: '1.0'
  contact:
    name: qa
    url: https://swagger.io/specification/#definitions
    email: email@redocly.com

paths:
  /pet/findByStatus:
    get:
      operationId: example
      responses:
        '200':
          description: example description.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    description: Will be use.
                    type: string
                  description:
                    description: Some description.
                    type: string
