openapi: 3.0.0
info:
  title: Example OpenAPI 3 definition.
  version: 1.0
  contact:
    name: qa
    url: https://swagger.io/specification/#definitions
    email: email@redoc.ly
paths:
  /pets/findByStatus:
    get:
      operationId: example
      summary: summary example
  /men/getList:
    get:
      operationId: list id
      summary: get men lists
  /statuses/getFirst:
    get:
      operationId: status id
      summary: get first status
