---
openapi: 3.0.1
info:
  title: TEST
  description: TEST
  version: v1
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://petstore.swagger.io/v1
security: []
components:
  schemas:
    Test:
      nullable: true
paths:
  /test:
    get:
      summary: test
      operationId: test
      responses:
        '202':
          description: Test
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Test'
              example: {}
        '400':
          description: An error response
