openapi: 3.0.0
info:
  title: Example OpenAPI 3 definition.
  version: 1.0
  contact: blah #Contact object should contain certain fixed fields

paths:
  /pet/findByStatus:
    get:
      responses:
        '200':
          description: example description