openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition.
  version: 1.0

paths:
  /pet/findByStatus:
    get:
      summary: Finds pets by Status
      tags:
        - pets
      responses:
        '200':
          description: example description
  /pet:
    post:
      summary: Adds a new pet to the store
      tags:
        - pets
      responses:
        '200':
          description: example description
  /store/inventory:
    get:
      summary: Returns pet inventories
      tags:
        - store
      esponses:
        '200':
          description: example description
tags:
  - name: pets
    description: Everything about your Pets
    externalDocs:
      url: http://docs.my-api.com/pet-operations.htm
  - name: store
    description: Access to Petstore orders
    externalDocs:
      url: http://docs.my-api.com/store-orders.htm