openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0

servers:
  - url: https://development.com/v1

paths:
  '/pet/last':
    get:
      summary: example pet
      operationId: petId
      responses:
        '200':
          description: pet example
  /v1/pets/{id}:
    parameters:
      - name: Accept-Language
        in: header
        description: 'The language you prefer for messages'
        example: en-US
        required: false
        schema:
          type: string
          default: en-AU
  /men/{mId}:
    get:
      operationId: list id
      summary: get men lists
  /statuses:
    get:
      operationId: status id
      summary: get first status
  /health: # should be ignored as it's the last segment and the ignoreLastPathSegment option is set to true
    get: 
      operationId: status
      summary: get health status
