openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0

servers:
  - url: https://development.com/v1

paths:
  '/pet':
    get:
      summary: example pet
      operationId: petId
      responses:
        '200':
          description: pet example
  /v1/pets:
    parameters:
      - name: Accept-Language
        in: header
        description: 'The language you prefer for messages'
        example: en-US
        required: false
        schema:
          type: string
          default: en-AU
