openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition. Valid.
  version: 1.0

servers:
- url: https://development.com/v1

paths:
  '/api/user/{}/profie':
    get:
      responses:
        '200':
          description: example description