openapi: 3.0.0
info:
  title: Example OpenAPI 3 definition.
  version: 1.0
  contact:
    name: qa
    url: https://swagger.io/specification/#definitions
    email: email@redoc.ly

paths:
  /pet/findByStatus:
    get:
      responses:
        '200':
          description: example description