openapi: 3.0.0
info:
  title: Example OpenAPI 3 definition.
  version: 1.0.0
  description: 

paths:
  '/ping/{id}/{test}':
    get:
      parameters:
        - in: path
          name: test_id
          description: User id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: example description