openapi: 3.0.2
info:
  title: Example OpenAPI 3 definition.
  version: 1.0

paths:
  '/api/user/{userId}/profie':
    get:
      parameters:
        - in: path
          name: userId
          description: User id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: example description