name: Snapshot Release

on:
  pull_request:
    types: [labeled]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  release-snapshot:
    if: github.event.label.name == 'snapshot'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      # id-token: write # Required for OIDC

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: Update package versions
        run: |
          TIMESTAMP=$(date +%s)
          VERSION="0.0.0-snapshot.$TIMESTAMP"

          # Update Core package version
          jq ".version = \"$VERSION\"" packages/core/package.json > tmp.json && mv tmp.json packages/core/package.json

          # Update Respect Core package version and dependencies
          jq ".version = \"$VERSION\"" packages/respect-core/package.json > tmp.json && mv tmp.json packages/respect-core/package.json
          jq ".dependencies[\"@redocly/openapi-core\"] = \"$VERSION\"" packages/respect-core/package.json > tmp.json && mv tmp.json packages/respect-core/package.json

          # Update CLI package version and dependencies
          jq ".version = \"$VERSION\"" packages/cli/package.json > tmp.json && mv tmp.json packages/cli/package.json
          jq ".dependencies[\"@redocly/openapi-core\"] = \"$VERSION\"" packages/cli/package.json > tmp.json && mv tmp.json packages/cli/package.json
          jq ".dependencies[\"@redocly/respect-core\"] = \"$VERSION\"" packages/cli/package.json > tmp.json && mv tmp.json packages/cli/package.json

          # Add comment with installation instructions
          COMMENT="üì¶ A new experimental üß™ version **v$VERSION** of Redocly CLI has been published for testing.

          Install with NPM:
          \`\`\`bash
          npm install @redocly/cli@$VERSION
          # or
          npm install @redocly/openapi-core@$VERSION
          # or
          npm install @redocly/respect-core@$VERSION
          \`\`\`

          ‚ö†Ô∏è Note: This is a development build and may contain unstable features."

          gh pr comment $PR_NUMBER --body "$COMMENT"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}

      - name: Install dependencies
        run: npm install

      - name: Build packages
        run: npm run compile

      - name: Publish snapshot packages
        run: |
          git diff

          cd packages/core
          npm publish --tag snapshot
          sleep 10

          cd ../respect-core
          npm publish --tag snapshot
          sleep 10

          cd ../cli
          npm publish --tag snapshot
