name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

env:
  CI: true
  REDOCLY_TELEMETRY: off

jobs:
  build-and-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Typecheck
        run: npm run typecheck
      - name: Unit Tests
        run: npm run unit

      - name: Coverage Report
        if: always() # Also generate the report if tests are failing
        continue-on-error: true
        uses: davelosert/vitest-coverage-report-action@v2

      - name: E2E Tests
        run: npm run e2e

  cli-package-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Prepare CLI and Core packages
        run: npm run pack:prepare
      - name: Install CLI Package
        run: npm install -g redocly-cli.tgz
      - name: Redocly version
        run: redocly --version
      - name: Definition test
        run: redocly lint resources/rebilly.yaml --format=stylish

  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 24
          cache: npm
      - name: Install dependencies
        run: npm ci
      - run: npm run eslint
      - run: npm run prettier:check
