name: Build and Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  # build-and-unit:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Cache dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: npm-${{ hashFiles('package-lock.json') }}
  #         restore-keys: |
  #           npm-${{ hashFiles('package-lock.json') }}
  #           npm-
  #     - name: Environments
  #       run: |
  #         echo
  #         echo Using Node $(node -v), NPM $(npm -v)
  #         echo
  #     - name: Install dependencies
  #       run: npm ci
  #       env:
  #         CI: true
  #     - name: Typecheck
  #       run: npm run typecheck
  #     - name: Unit Tests
  #       run: npm run jest -- --silent --ci --testLocationInResults --bail --coverage
  #     - name: E2E Tests
  #       run: npm run e2e
  #       env:
  #         CI: true

  # cli-package-test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Cache dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: npm-${{ hashFiles('package-lock.json') }}
  #         restore-keys: |
  #           npm-${{ hashFiles('package-lock.json') }}
  #           npm-
  #     - name: Environments
  #       run: |
  #         echo
  #         echo Using Node $(node -v), NPM $(npm -v)
  #         echo
  #     - name: Install dependencies
  #       run: npm ci
  #       env:
  #         CI: true
  #     - name: Pack CORE package
  #       run: npm pack ./packages/core
  #     - name: Use local CORE package in CLI
  #       run: |
  #         version=$(cat ./packages/core/package.json | jq '.version' | tr -d '"')
  #         jq '.dependencies."@redocly/openapi-core" = $packagefile' ./packages/cli/package.json --arg packagefile file:./redocly-openapi-core-$version.tgz > package.json.tmp && mv package.json.tmp ./packages/cli/package.json
  #     - name: Output package.json
  #       run: cat ./packages/cli/package.json

  #     - name: Prepare CLI package
  #       run: npm run pack:prepare
  #     - name: Install CLI Package
  #       run: npm install -g redocly-cli.tgz
  #     - name: Redocly version
  #       run: redocly --version
  #     - name: Definition test
  #       run: redocly lint packages/core/src/benchmark/benches/rebilly.yaml --format=stylish

  
  docker-container-test:
    runs-on: ubuntu-latest
    container:
      image: node:12
      env:
        CI: true
    steps:
      - uses: actions/checkout@v3
      - name: Install JQ
        run: sudo apt-get update && sudo apt-get install jq
      - name: Environments
        run: |
          echo
          echo Using Node $(node -v), NPM $(npm -v)
          echo
      - name: Install dependencies
        run: npm ci
        env:
          CI: true
     
      - name: Pack CORE package
        run: npm pack ./packages/core
      - name: Use local CORE package in CLI
        run: |
          version=$(cat ./packages/core/package.json | jq '.version' | tr -d '"')
          jq '.dependencies."@redocly/openapi-core" = $packagefile' ./packages/cli/package.json --arg packagefile file:./redocly-openapi-core-$version.tgz > package.json.tmp && mv package.json.tmp ./packages/cli/package.json
      - name: Output package.json
        run: cat ./packages/cli/package.json
      - name: Prepare CLI package
        run: npm run pack:prepare
      - name: Run cli from NPX
        run: npx redocly-cli.tgz --version
      
  # coverage-report:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Cache dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: npm-${{ hashFiles('package-lock.json') }}
  #         restore-keys: |
  #           npm-${{ hashFiles('package-lock.json') }}
  #           npm-
  #     - name: Coverage Report
  #       uses: artiomtr/jest-coverage-report-action@v2.0.8
  #       continue-on-error: true
  #       with:
  #         skip-step: none
  #         annotations: none
  #         test-script: npm run jest

  # prettier-check:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Cache dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: npm-${{ hashFiles('package-lock.json') }}
  #         restore-keys: |
  #           npm-${{ hashFiles('package-lock.json') }}
  #           npm-
  #     - name: Install dependencies
  #       run: npm ci
  #       env:
  #         CI: true
  #     - run: npm run prettier:check

  # eslint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Cache dependencies
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: npm-${{ hashFiles('package-lock.json') }}
  #         restore-keys: |
  #           npm-${{ hashFiles('package-lock.json') }}
  #           npm-
  #     - name: Install dependencies
  #       run: npm ci
  #       env:
  #         CI: true
  #     - run: npm run eslint
